### ISSUE TITLE
安装依赖包有报错

### ISSUE THREAD

**Issue by aion1998** [pengyou200902/Doctor-Friende#20]
```
 ERROR: Command errored out with exit status 1:
     command: 'c:\users\administrator\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\userdata\\temp\\pip-install-dtx8sdds\\blis\\setup.py'"'"'; __file__='"'"'D:\\userdata\\temp\\pip-install-dtx8sdds\\blis\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'D:\userdata\temp\pip-pip-egg-info-b1qtua_5'
         cwd: D:\userdata\temp\pip-install-dtx8sdds\blis\
    Complete output (238 lines):
    WARNING: The wheel package is not available.
        ERROR: Command errored out with exit status 1:
         command: 'c:\users\administrator\appdata\local\programs\python\python39\python.exe' 'c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'D:\userdata\temp\tmpbvkxus8c'
             cwd: D:\userdata\temp\pip-wheel-6mr61kyx\numpy
        Complete output (200 lines):
        Running from numpy source directory.
        setup.py:470: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
          run_build = parse_setuppy_commands()

······

```

这些大概是啥错？ 俺不是很懂，安装依赖包的时候报错的
----------
Python版本：3.9.0  
系统环境：Windows10企业版__

**Comment by pengyou200902** [comment]
你的环境里有没有wheel这个包

**Comment by aion1998** [comment]
```
  ERROR: Command errored out with exit status 1:
     command: 'c:\users\administrator\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\userdata\\temp\\pip-install-ekxshyyq\\blis\\setup.py'"'"'; __file__='"'"'D:\\userdata\\temp\\pip-install-ekxshyyq\\blis\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'D:\userdata\temp\pip-pip-egg-info-cvmkxamd'
         cwd: D:\userdata\temp\pip-install-ekxshyyq\blis\
    Complete output (237 lines):
        ERROR: Command errored out with exit status 1:
         command: 'c:\users\administrator\appdata\local\programs\python\python39\python.exe' 'c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'D:\userdata\temp\tmpm7u868fa'
             cwd: D:\userdata\temp\pip-wheel-cax5y4mm\numpy
        Complete output (200 lines):
        Running from numpy source directory.
        setup.py:470: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
          run_build = parse_setuppy_commands()
        Processing numpy/random\_bounded_integers.pxd.in
        Processing numpy/random\bit_generator.pyx
        Processing numpy/random\mtrand.pyx
        Processing numpy/random\_bounded_integers.pyx.in
        Processing numpy/random\_common.pyx
        Processing numpy/random\_generator.pyx
        Processing numpy/random\_mt19937.pyx
        Processing numpy/random\_pcg64.pyx
        Processing numpy/random\_philox.pyx
        Processing numpy/random\_sfc64.pyx
        Cythonizing sources
        blas_opt_info:
        blas_mkl_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries mkl_rt not found in ['c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\libs']
          NOT AVAILABLE

        blis_info:
          libraries blis not found in ['c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\libs']
          NOT AVAILABLE

        openblas_info:
          libraries openblas not found in ['c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\libs']
        get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
        customize GnuFCompiler
        Could not locate executable g77
        Could not locate executable f77
        customize IntelVisualFCompiler
        Could not locate executable ifort
        Could not locate executable ifl
        customize AbsoftFCompiler
        Could not locate executable f90
        customize CompaqVisualFCompiler
        Could not locate executable DF
        customize IntelItaniumVisualFCompiler
        Could not locate executable efl
        customize Gnu95FCompiler
        Could not locate executable gfortran
        Could not locate executable f95
        customize G95FCompiler
        Could not locate executable g95
        customize IntelEM64VisualFCompiler
        customize IntelEM64TFCompiler
        Could not locate executable efort
        Could not locate executable efc
        customize PGroupFlangCompiler
        Could not locate executable flang
        don't know how to compile Fortran code on platform 'nt'
          NOT AVAILABLE

        atlas_3_10_blas_threads_info:
        Setting PTATLAS=ATLAS
          libraries tatlas not found in ['c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\libs']
          NOT AVAILABLE

        atlas_3_10_blas_info:
          libraries satlas not found in ['c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\libs']
          NOT AVAILABLE

        atlas_blas_threads_info:
        Setting PTATLAS=ATLAS
          libraries ptf77blas,ptcblas,atlas not found in ['c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\libs']
          NOT AVAILABLE

        atlas_blas_info:
          libraries f77blas,cblas,atlas not found in ['c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\libs']
          NOT AVAILABLE

        accelerate_info:
          NOT AVAILABLE

        D:\userdata\temp\pip-wheel-cax5y4mm\numpy\numpy\distutils\system_info.py:1914: UserWarning:
            Optimized (vendor) Blas libraries are not found.
            Falls back to netlib Blas library which has worse performance.
            A better performance should be easily gained by switching
            Blas library.
          if self._calc_info(blas):
        blas_info:
          libraries blas not found in ['c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\libs']
          NOT AVAILABLE

        D:\userdata\temp\pip-wheel-cax5y4mm\numpy\numpy\distutils\system_info.py:1914: UserWarning:
            Blas (http://www.netlib.org/blas/) libraries not found.
            Directories to search for the libraries can be specified in the
            numpy/distutils/site.cfg file (section [blas]) or by setting
            the BLAS environment variable.
          if self._calc_info(blas):
        blas_src_info:
          NOT AVAILABLE

        D:\userdata\temp\pip-wheel-cax5y4mm\numpy\numpy\distutils\system_info.py:1914: UserWarning:
            Blas (http://www.netlib.org/blas/) sources not found.
            Directories to search for the sources can be specified in the
            numpy/distutils/site.cfg file (section [blas_src]) or by setting
            the BLAS_SRC environment variable.
          if self._calc_info(blas):
          NOT AVAILABLE

        non-existing path in 'numpy\\distutils': 'site.cfg'
        lapack_opt_info:
        lapack_mkl_info:
          libraries mkl_rt not found in ['c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\libs']
          NOT AVAILABLE

        openblas_lapack_info:
          libraries openblas not found in ['c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\libs']
          NOT AVAILABLE

        openblas_clapack_info:
          libraries openblas,lapack not found in ['c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\libs']
          NOT AVAILABLE

        flame_info:
          libraries flame not found in ['c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\libs']
          NOT AVAILABLE

        atlas_3_10_threads_info:
        Setting PTATLAS=ATLAS
          libraries lapack_atlas not found in c:\users\administrator\appdata\local\programs\python\python39\lib
          libraries tatlas,tatlas not found in c:\users\administrator\appdata\local\programs\python\python39\lib
          libraries lapack_atlas not found in C:\
          libraries tatlas,tatlas not found in C:\
          libraries lapack_atlas not found in c:\users\administrator\appdata\local\programs\python\python39\libs
          libraries tatlas,tatlas not found in c:\users\administrator\appdata\local\programs\python\python39\libs
        <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
          NOT AVAILABLE

        atlas_3_10_info:
          libraries lapack_atlas not found in c:\users\administrator\appdata\local\programs\python\python39\lib
          libraries satlas,satlas not found in c:\users\administrator\appdata\local\programs\python\python39\lib
          libraries lapack_atlas not found in C:\
          libraries satlas,satlas not found in C:\
          libraries lapack_atlas not found in c:\users\administrator\appdata\local\programs\python\python39\libs
          libraries satlas,satlas not found in c:\users\administrator\appdata\local\programs\python\python39\libs
        <class 'numpy.distutils.system_info.atlas_3_10_info'>
          NOT AVAILABLE

        atlas_threads_info:
        Setting PTATLAS=ATLAS
          libraries lapack_atlas not found in c:\users\administrator\appdata\local\programs\python\python39\lib
          libraries ptf77blas,ptcblas,atlas not found in c:\users\administrator\appdata\local\programs\python\python39\lib
          libraries lapack_atlas not found in C:\
          libraries ptf77blas,ptcblas,atlas not found in C:\
          libraries lapack_atlas not found in c:\users\administrator\appdata\local\programs\python\python39\libs
          libraries ptf77blas,ptcblas,atlas not found in c:\users\administrator\appdata\local\programs\python\python39\libs
        <class 'numpy.distutils.system_info.atlas_threads_info'>
          NOT AVAILABLE

        atlas_info:
          libraries lapack_atlas not found in c:\users\administrator\appdata\local\programs\python\python39\lib
          libraries f77blas,cblas,atlas not found in c:\users\administrator\appdata\local\programs\python\python39\lib
          libraries lapack_atlas not found in C:\
          libraries f77blas,cblas,atlas not found in C:\
          libraries lapack_atlas not found in c:\users\administrator\appdata\local\programs\python\python39\libs
          libraries f77blas,cblas,atlas not found in c:\users\administrator\appdata\local\programs\python\python39\libs
        <class 'numpy.distutils.system_info.atlas_info'>
          NOT AVAILABLE

        lapack_info:
          libraries lapack not found in ['c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\libs']
          NOT AVAILABLE

        D:\userdata\temp\pip-wheel-cax5y4mm\numpy\numpy\distutils\system_info.py:1748: UserWarning:
            Lapack (http://www.netlib.org/lapack/) libraries not found.
            Directories to search for the libraries can be specified in the
            numpy/distutils/site.cfg file (section [lapack]) or by setting
            the LAPACK environment variable.
          return getattr(self, '_calc_info_{}'.format(name))()
        lapack_src_info:
          NOT AVAILABLE

        D:\userdata\temp\pip-wheel-cax5y4mm\numpy\numpy\distutils\system_info.py:1748: UserWarning:
            Lapack (http://www.netlib.org/lapack/) sources not found.
            Directories to search for the sources can be specified in the
            numpy/distutils/site.cfg file (section [lapack_src]) or by setting
            the LAPACK_SRC environment variable.
          return getattr(self, '_calc_info_{}'.format(name))()
          NOT AVAILABLE

        numpy_linalg_lapack_lite:
          FOUND:
            language = c
            define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]

        c:\users\administrator\appdata\local\programs\python\python39\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
          warnings.warn(msg)
        running dist_info
        running build_src
        build_src
        building py_modules sources
        creating build
        creating build\src.win-amd64-3.9
        creating build\src.win-amd64-3.9\numpy
        creating build\src.win-amd64-3.9\numpy\distutils
        building library "npymath" sources
        error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
        ----------------------------------------
    ERROR: Command errored out with exit status 1: 'c:\users\administrator\appdata\local\programs\python\python39\python.exe' 'c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'D:\userdata\temp\tmpm7u868fa' Check the logs for full command output.
    Traceback (most recent call last):
      File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "c:\users\administrator\appdata\local\programs\python\python39\lib\subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'D:\\userdata\\temp\\tmpnfg40loe', '--quiet', 'numpy>=1.15.0']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\userdata\temp\pip-install-ekxshyyq\blis\setup.py", line 239, in <module>
        setup(
      File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 164, in setup
        _install_setup_requires(attrs)
      File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 159, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py", line 699, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 779, in resolve
        dist = best[req.key] = env.best_match(
      File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 1064, in best_match
        return self.obtain(req, installer)
      File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 1076, in obtain
        return installer(requirement)
      File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py", line 758, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\setuptools\installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'D:\\userdata\\temp\\tmpnfg40loe', '--quiet', 'numpy>=1.15.0']' returned non-zero exit status 1.
    BLIS_COMPILER? None
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output
```
-----------------
wheel执行了安装后还有错误...是我哪些版本对不上吗

**Comment by pengyou200902** [comment]
你是如何搭建你的开发环境的能说说看吗

**Comment by aion1998** [comment]
> 你是如何搭建你的开发环境的能说说看吗

一开始是安装的2.x，后来升级为了3.9，但是pip没跟着升级
当我第一次安装你这个依赖的时候，pip是老版本，报错后我升级了pip，然后还是不行
目前就是这么一个状况

**Comment by pengyou200902** [comment]
> > 你是如何搭建你的开发环境的能说说看吗
> 
> 一开始是安装的2.x，后来升级为了3.9，但是pip没跟着升级
> 当我第一次安装你这个依赖的时候，pip是老版本，报错后我升级了pip，然后还是不行
> 目前就是这么一个状况

如果你用python2的pip升级了pip自己，那有可能你还是在用python2的pip在安装，而不是python3的pip？

**Comment by aion1998** [comment]
> > > 你是如何搭建你的开发环境的能说说看吗
> > 
> > 
> > 一开始是安装的2.x，后来升级为了3.9，但是pip没跟着升级
> > 当我第一次安装你这个依赖的时候，pip是老版本，报错后我升级了pip，然后还是不行
> > 目前就是这么一个状况
> 
> 如果你用python2的pip升级了pip自己，那有可能你还是在用python2的pip在安装，而不是python3的pip？

升级为3之后我才升级的pip，应该不是这个问题

**Comment by pengyou200902** [comment]
可以cmd输入where pip确认下，如果是py3的pip的话，可以试试新建一个环境以后先安装wheel和setuptools，然后再pip install -r requirements.txt，确认用的是我最新上传的requirements.txt，之前传过一个版本里面有“@file”内容是不对的。

**Comment by aion1998** [comment]
> 可以cmd输入where pip确认下，如果是py3的pip的话，可以试试新建一个环境以后先安装wheel和setuptools，然后再pip install -r requirements.txt，确认用的是我最新上传的requirements.txt，之前传过一个版本里面有“@file”内容是不对的。

好吧，谢谢

**Comment by pengyou200902** [comment]
有装成功吗？

**Comment by aion1998** [comment]
> 有装成功吗？
没有，等下班了回家用我自己电脑再试试
